import ccircle
import random
from time import sleep

window = ccircle.Window("heckin loadsa circles")

baseSize = 16

def createCircle():
    size = baseSize + random.randint(-4, 4)
    winWid, winHgt = window.getSize()
    window.drawCircle(random.randint(0 + size, winWid - size), random.randint(0 + size, winHgt - size), size,
                      random.uniform(0, 1), random.uniform(0, 1), random.uniform(0, 1))
    return None

window.clear(0, 0, 0)
while window.isOpen():
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    createCircle()
    window.update()
    sleep(0.035)